[package]
name = "shared_commands"
version = "0.0.0"
authors = [ "You" ]
description = ""
edition = "2021"
rust-version = "1.60"

[dependencies]
reqwest = "0.11.18"
jsonwebtoken = "8"
serde = {version = "1.0", features = ["derive"] }
tauri = { version = "1.4.0" }
lazy_static = "1.4.0"
